security:
  access_denied_url: /
  encoders:
    FOS\UserBundle\Model\UserInterface: sha512

  role_hierarchy:
    ROLE_ADMIN:       ROLE_USER
    ROLE_SUPER_ADMIN: [ROLE_USER, ROLE_ADMIN, ROLE_ALLOWED_TO_SWITCH]

  providers:
    fos_userbundle:
      id: fos_user.user_provider.username


  firewalls:
    main:
      pattern: ^/
      auth: true
      stateless: true
      anonymous: ~
      #logout: true


  access_control:
            - { path: ^/api/v1/users, roles: IS_AUTHENTICATED_ANONYMOUSLY }
            - { path: ^/api/v1/, roles: IS_AUTHENTICATED_FULLY }

