<?php

namespace Scazz\LearnVocabBundle\Entity;

use Doctrine\ORM\EntityRepository;
use Doctrine\ORM\Query\Expr;


/**
 * SubjectTemplateRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class SubjectTemplateRepository extends EntityRepository
{
	public function findAllUnusedTemplatesForUser(User $user) {
		$q = $this->createQueryBuilder('st');

		$joinCondition =
			$q->expr()->andx(
				$q->expr()->eq('st.name', 's.name'),
				$q->expr()->eq('s.user', ':user')
			);

		$q->select('st');
		$q->leftJoin('ScazzLearnVocabBundle:Subject', 's', Expr\Join::WITH, $joinCondition );
		$q->where('s.id is null');
		$q->setParameter('user', $user);
		return $q->getQuery()->getResult();
	}
}
