<?php

namespace Scazz\LearnVocabBundle\Entity;

use Doctrine\ORM\EntityRepository;
use Doctrine\ORM\Query\Expr;


/**
 * SubjectTemplateRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class SubjectTemplateRepository extends EntityRepository
{
	public function findAllUnusedTemplates() {
		$q = $this->createQueryBuilder('st');

		$q->select('st');
		$q->leftJoin('ScazzLearnVocabBundle:Subject', 's', Expr\Join::WITH, $q->expr()->eq('st.name','s.name'));
		$q->where('s.id is null');
		return $q->getQuery()->getResult();
	}
}
