<?php

namespace Scazz\LearnVocabBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * SubjectTemplateRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class SubjectTemplateRepository extends EntityRepository
{
}
