<?php

namespace Scazz\LearnVocabBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * TopicRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TopicRepository extends EntityRepository
{


	public function findAllByUser(User $user) {
		$q = $this->createQueryBuilder('t');
		$q->where('t.user = :user')
		  ->setParameter('user', $user);

		return $q->getQuery()->getResult();
	}

	public function findAllByUserAndIds(User $user, array $ids) {
		$q = $this->createQueryBuilder('t');

		$q->where(
			$q->expr()->andX(
				't.user = :user',
				't.id IN (:ids)'
			)
		)
			->setParameter('user', $user)
			->setParameter('ids', $ids);

		return $q->getQuery()->getResult();
	}
}
