<?php

namespace Scazz\LearnVocabBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * VocabRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class VocabRepository extends EntityRepository
{
	public function findAllByUser(User $user) {
		$q = $this->createQueryBuilder('v');
		$q->where('v.user = :user')
		  ->setParameter('user', $user);

		return $q->getQuery()->getResult();
	}

	public function findAllByUserAndIds(User $user, array $ids) {
		$q = $this->createQueryBuilder('v')
			->where('v.user = :user')
			->andWhere('v.id in (:ids)')
			->setParameter('user', $user)
			->setParameter('ids', $ids);

		return $q->getQuery()->getResult();
	}
}
